language: dart
sudo: required
addons:
  chrome: stable
dart:
  - stable
dart_task:
  # TODO enable once tests are working
  # - test: --platform vm
  # - test: --platform chrome
  - dartanalyzer: lib example test
  - dartfmt: true
