analyzer.files: 
  - lib/common.dart
  - lib/server.dart
  - lib/browser.dart
  - example/repos.dart
  - example/organization.dart
  - example/users.dart
  - example/user_info.dart
  - example/languages.dart
  - example/oauth2.dart
  - example/releases.dart
  - example/common.dart
check.tasks: 
  - analyze
  - test
docs.output: out/docs
test.file: test/all_tests.dart
