analyzer.files: 
  - lib/client.dart
  - example/repos.dart
  - example/organization.dart
  - example/users.dart
  - example/user_info.dart
check.tasks: 
  - analyze
  - test
docs.output: out/docs
test.file: test/all_tests.dart
